### ISSUE TITLE
toWkt output

### ISSUE THREAD

**Issue by taviroquai** [cschwarz/wkx#10]
Hi,

This is the geometry object:
```
Point {
    srid: undefined, 
    hasZ: true, 
    hasM: false, 
    x: 389671.879, 
    y: 263437.527,
    z: 0
}
```

When I call .toWkt() it outputs:
`POINT Z (389671.879 263437.527 0)`

It shouldn't be POINT(389671.879 263437.527 0) ?

Thanks :)

**Comment by cschwarz** [comment]
According to https://en.wikipedia.org/wiki/Well-known_text and PostGIS, POINT Z should be fine. Do you have any issues with it?

**Comment by taviroquai** [comment]
Yes, when passing this output to OpenLayers 3, ie:

ol.format.WKT.readGeometry(wkx_lib_wkt_output);

It does not recognize the WKT format.

**Comment by cschwarz** [comment]
Seems like Open Layers 3 only supports 2D geometries.

Depending on how you get your geometries, you can either use ST_Force2D if you use PostGIS or set hasZ to false on your geometry objects.

**Comment by taviroquai** [comment]
Thank you!

I think setting the hasZ will work fine as I'm not getting data from Postgis.

I will try and give feedback :)

**Comment by taviroquai** [comment]
Setting hasZ and hasM to false makes 2D geomety which is what OL3 WKT format currently supports :)
