### ISSUE TITLE
Error with WKB parsing

### ISSUE THREAD

**Issue by YonatanKra** [cschwarz/wkx#13]
Hi,
I'm trying to convert geoJson to wkb.  It doesn't really work (or I don't know what to do with it...).
I do the following:
1) Get GeoJson.
2) Parse it into `geometry`.
3) Do `wkbBuffer = geometry.toWkb();`
4) try to parse the `buffer` - ` wkx.Geometry.parse(wkbBuffer);`
It gives me an error:
```
jQuery.Deferred exception: Trying to access beyond buffer length RangeError: Trying to access beyond buffer length
```
Here's the plnkr: https://plnkr.co/edit/4EyqlbUPDyS81sTHMWWt?p=preview

**Comment by cschwarz** [comment]
Instead of

```javascript
var wkbBuffer = new Buffer(geometry.toWkb().join(''));
```

you can either reuse the buffer directly
```javascript
var wkbBuffer = geometry.toWkb();
```

or create a copy - but without using join

```javascript
var wkbBuffer = new Buffer(geometry.toWkb());
```

**Comment by YonatanKra** [comment]
Works, thanks :)
