### ISSUE TITLE
getting invalid geoJSON

### ISSUE THREAD

**Issue by sumanindusnet** [cschwarz/wkx#14]
I am passing a WKB in hexadecimal format and getting coordinates like this 405319.7331131318, 4668436.547074934 which I think is not valid coordinates.
the procedure I am following is like this 

var wkbBuffer = new Buffer('hexadecimal WKB', 'hex');
var geometry = wkx.Geometry.parse(wkbBuffer);
console.log(geometry.toGeoJSON());

Could you please help me out here...

**Comment by codingmiao** [comment]
I have transformed it with wgs84 Mercator coordinate system, the results is 112.854613347E,42.145529064N,is it right?

**Comment by sumanindusnet** [comment]
Yes it seems to be correct. What am I suppose to do to get this as result?

**Comment by cschwarz** [comment]
Depending on how you get to your WKB data you can transform it either in the database or on client side.
