### ISSUE TITLE
Move @types/node to devDependency

### ISSUE THREAD

**Issue by ddura** [cschwarz/wkx#15]
Is there a particular reason why the @types/node is being specified as a production dependency? I have a typescript project that uses a library that has a dependency on wkx. Because wkx is installing the @types/node module it is playing havoc with my typescript project (i have @types/node included somewhere else and it is causing duplicate identifier issues with the tsc compiler.). Can the module be moved to be only a dev dependency?

**Comment by mbugbee** [comment]
+1

**Comment by cschwarz** [comment]
Basically because of this https://github.com/Microsoft/types-publisher/issues/81.

Which TypeScript version are you using?

I think the main issue is that the version is fixed to 6.x and that will conflict with newer versions.

Please give the updated version a try.
