### ISSUE TITLE
What is the expected Format for WKT strings?

### ISSUE THREAD

**Issue by VeitSanner** [cschwarz/wkx#25]
[Spatial Reference](https://spatialreference.org) provides multiple WKT string formats but none of those are accepted by wkx.

E.g. the provided `OGC WKT` string for [epsg projection 4326 - wgs 84](https://spatialreference.org/ref/epsg/wgs-84/) is the following:

```
GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]
```
This string is not accepted by wkx. What is the expected WKT format?

**Comment by cschwarz** [comment]
wkx is for well-known text representation of geometries rather than coordinate systems:

https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry
