### ISSUE TITLE
convert FeatureCollection

### ISSUE THREAD

**Issue by gagan-bansal** [cschwarz/wkx#7]
Hi, Very nice module. 
does it make sense to convert FeatureCollection to twkb. I mean instead of gzip, compress whole geojson file to twkb. 
If yes, how can it be done both ways?

**Comment by cschwarz** [comment]
Hi, yes thats make sense and is possible, but currently it is not a one-liner.

Basically you need to iterate over the feature array, parse the geometry part and store it in a wkx GeometryCollection or in one of the Multi* geometry types. Then you can convert it into a compact twkb buffer and vice versa.

The reason is that this library currently doesn't handle the attribute part of geojson as it doesn't exist in any of the other supported formats. Maybe I'm going to add support for attributes in 1.0.

**Comment by nicklasaven** [comment]
Hi, I also wany to say thanks for this library. It looks really nice.

About twkb it doesn't hold attributes either, only id. It has been discussed to att attributes but it wpuld increase complexity a lot. I also have the idea that keeping th attributes outside of the twkb makes it easier to find new ways of using it. And there is nothing in the way of wraping something around twkb that holds the attributes.

**Comment by gagan-bansal** [comment]
@cschwarz thanks for quick reply, looking for ver 1.0. Hope you have seen [twkb.js](https://github.com/TWKB/twkb.js)
@nicklasaven thanks  for update.
What could be another option for geojson compression better than gzip?

**Comment by nicklasaven** [comment]
As always it depends on the situation :-). If the heavy part of your data is the geometries, you could absolutely encode it as twkb. You can store it as a file on disc and read it with FileAPI. If it is big you might be interested in an indexed variant. It follows the same specification, but the geometries is arranged as a quad tree. I haven't put the encoding code on github yet, but I will when I get time to clean it up. That is an extension to PostGIS to encode twkb this way.

Maybe that could be something for the wkx library too?

You can see a demo here :http://twkb.jordogskog.no/offlineMapV2/
There is a link to the twkb-file at the top. 

But the attributes was the question.
If they are just a small part of the total you can send that part as gziped json. The id of the geometries is stored in the twkb so you can join them together at the client.

But there is also another format out there htat might be of interest. It is geobuf. A MapBox format that in some ways is similar to twkb. It uses the same type of delta encoding and also packs attributes in a protobuffer format. 
https://github.com/mapbox/geobuf

**Comment by gagan-bansal** [comment]
@nicklasaven thanks for the detailed explanation, Storing geometries' ids with in twkb is also good idea and rest as json.
I'll go through the geobuf. I'll go through [pbf format](http://wiki.openstreetmap.org/wiki/PBF_Format)  also.
